name: eedi2
channels:
  - conda-forge
dependencies:
  - pip=24.3.1
  - python=3.10.15
  - pip:
    - black
    - isort
    - jupyter
    - matplotlib
    - numpy
    - pandas
    - requests
    - scikit-learn
    - scipy
    - seaborn
    - sentence-transformers==3.1.1
    - torch --index-url https://download.pytorch.org/whl/cu121
    - torchaudio --index-url https://download.pytorch.org/whl/cu121
    - torchvision --index-url https://download.pytorch.org/whl/cu121
    - tqdm
    - transformers==4.45.2
